version: '3.7'

services:
#    nest:
#        container_name: 'nest'
#        build:
#            context: .
#            target: development
#        volumes:
#            - .:/usr/src/app
#        ports:
#            - ${SERVER_PORT}:${SERVER_PORT}
#            - 9229:9229
#        command: npm run start:debug
#        depends_on:
#            - mongo
    mongo:
        image: mongo:latest
        container_name: 'mongo'
        volumes:
            - mongodb_data_container:/data/db
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - ${MONGO_PORT}:27017

networks:
    webnet:

volumes:
    mongodb_data_container:
